### ISSUE TITLE
Can I add 2-character state support?

### ISSUE THREAD

**Issue by FelicianoTech** [fegoa89/zipcodes#1]
The datasets have the state abbreviation but this module doesn't pull it in. Before I make the PR, since this repo hasn't been touched in awhile, I wanted to know if there's a chance it would be accepted.

**Comment by fegoa89** [comment]
Hi @felicianotech, thanks for your message. Sure, feel free to open a PR for it!

**Comment by fegoa89** [comment]
@felicianotech included as a new field called StateCode!
